apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapplication-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webappfordemo
  template:
    metadata:
      labels:
        app: webappfordemo
    spec:
      containers:
      - name: webapplicationfordemo
        image: webapplicationfordemo:latest
        imagePullPolicy: Never